# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: A life that made sense
email: michael0745@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My family and I took a road less traveled. This blog will be a journal
  concerning our new life in France. I hope to share some fun engineering
  projects also along the way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/soitgoes511/soitgoes511.github.io.git" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  soitgoes511
linkedin_username: mike-hinkle-054808a6

# Build settings
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin: "dark"
google_verify: ssubl9UP5EI0ed8OjDk5qABCNio_oCWbUmWPJlyGsu8
# paginate: 3
# paginate_path: "/blog/page:num/"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

author:
  name: "Mike Hinkle"
  avatar: "/assets/my_pic.png"
  bio: "_Ex-semiconductor engineer_, fascinated with **big data, analytics, data visualization, dashboarding & observability**.
       I am a father, husband, lifelong learner & tech nerd. More on me in the **ABOUT** section."
  location: "Bourgogne, France (CÃ´te-d'Or)"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/soitgoes511"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mike-hinkle-054808a6"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:michael0745@protonmail.com"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jemoji
  #- jekyll-paginate

# markdown: redcarpet
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
timezone: Europe/Paris
future: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/soitgoes511"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mike-hinkle-054808a6"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
